name: Force Reboot

on: workflow_dispatch

jobs:
  build:
    name: Force Reboot

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        node-version: [16.12.x]

    steps:
    - name: Reboot Server
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://server.rair.land/reboot/force'
        method: 'POST'
        data: '{ "secret": "${{ secrets.WEBHOOK_SECRET }}" }'
        preventFailureOnNoResponse: 'true'
        ignoreStatusCodes: '404,502'

    - name: Wait 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Reboot Done
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://server.rair.land/reboot/done'
        method: 'POST'
        data: '{ "secret": "${{ secrets.WEBHOOK_SECRET }}" }'
        preventFailureOnNoResponse: 'true'
