name: Release New Tags

on:
  push:
    tags:
      - 'v*' # Any pushed tag

jobs:
  build:
    name: Create Release

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm run setup:full

    - run: npm run lint

    - run: npm run build

    - uses: little-core-labs/get-git-tag@v3.0.1
      id: loadTagName

    - uses: pCYSl5EDgo/cat@master
      id: loadChangelog
      with:
        path: CHANGELOG-current.md

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.loadChangelog.outputs.text }}
        draft: false
        prerelease: false

    #- name: Deploy Server
    #  uses: AlexxNB/caprover-action@v1
    #  with:
    #    server: 'https://captain.server.rair.land'
    #    password: '${{ secrets.CAPROVER_PASSWORD }}'
    #    appname: 'game'

    #- name: Deploy to Netlify
    #  uses: nwtgck/actions-netlify@v1.1
    #  with:
    #    publish-dir: './client/dist'
    #    production-branch: master
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    deploy-message: "Deploy from GitHub Actions"
    #    enable-pull-request-comment: false
    #    enable-commit-comment: true
    #    overwrites-pull-request-comment: true
    #  env:
    #    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    #    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    #- name: Post to Reddit
    #  uses: bluwy/release-for-reddit-action@v1
    #  with:
    #    username: ${{ secrets.REDDIT_USERNAME }}
    #    password: ${{ secrets.REDDIT_PASSWORD }}
    #    app-id: ${{ secrets.REDDIT_APP_ID }}
    #    app-secret: ${{ secrets.REDDIT_APP_SECRET }}
    #    subreddit: Rasterkhann
    #    title: Rasterkhann ${{ steps.loadTagName.outputs.tag }} Update
    #    comment: ${{ steps.loadChangelog.outputs.text }}
    #    url: ${{ steps.create_release.outputs.html_url }}
    #    notification: true
